@extends('layouts.app')
@section('title','Visitor Log')
@section('subtitle','Every arrival, clearly organized.')
@section('content')
<div class="panel visitor-register">
<div class="register-heading"><div><span class="eyebrow">RECEPTION REGISTER</span><h2>Visit history <span class="record-count">{{ $visits->total() }}</span></h2></div><span class="register-note"><i data-icon="visits"></i> Your workplace, at a glance</span></div>
<div class="register-tabs" aria-label="Filter by visit status">@foreach([''=>'All visits','inside'=>'Currently inside','completed'=>'Checked out'] as $status=>$label)<a class="{{ request('status','') === $status ? 'selected' : '' }}" href="{{ request()->fullUrlWithQuery(['status'=>$status,'page'=>null]) }}" @if(request('status','') === $status) aria-current="page" @endif>{{ $label }}</a>@endforeach</div>
<form class="register-filters" role="search"><input type="hidden" name="status" value="{{ request('status') }}"><label class="register-search"><span>Find a visitor</span><input name="q" value="{{ request('q') }}" placeholder="Search name, ID, or host"></label><label><span>Arrival date</span><input type="date" name="date" value="{{ request('date') }}"></label><button class="btn primary">Apply filters</button>@if(request()->filled('q') || request()->filled('date') || request()->filled('status'))<a class="btn" href="{{ route('visits.index') }}">Clear</a>@endif</form>
<div class="table-wrap"><table class="visitor-table"><thead><tr><th>Visitor / identity</th><th>Host / purpose</th><th>Arrival & departure</th><th>Status</th><th>Manage visit</th></tr></thead><tbody>
@forelse($visits as $visit)<tr><td data-label="Visitor"><div class="person">@if($visit->photo_path)<a class="photo-link" href="{{ route('visits.photo',$visit) }}" data-view-photo aria-label="Open visitor photo"><img src="{{ route('visits.photo',$visit) }}" alt="{{ $visit->visitor_name }}"></a>@else<span class="avatar">{{ strtoupper(substr($visit->visitor_name,0,1)) }}</span>@endif<div><a class="visitor-name" href="{{ route('visits.show',$visit) }}">{{ $visit->visitor_name }}</a><small>{{ $visit->id_card_number }} <span class="pass-number">#{{ str_pad($visit->id,4,'0',STR_PAD_LEFT) }}</span></small></div></div></td><td data-label="Meeting"><b>{{ $visit->employee->name }}</b><small>{{ $visit->employee->company->name }}</small><span class="purpose-preview" title="{{ $visit->purpose }}">{{ Str::limit($visit->purpose,65) }}</span></td><td data-label="Arrival"><div class="arrival-time">{{ $visit->check_in_at->format('h:i A') }} <span>{{ $visit->check_in_at->format('d M Y') }}</span></div><small>{{ $visit->check_out_at ? 'Departed '.$visit->check_out_at->format('d M, h:i A') : 'Visit in progress' }}</small></td><td data-label="Status"><span class="badge {{ $visit->check_out_at?'gray':'green' }}">{{ $visit->check_out_at?'Checked out':'Inside now' }}</span></td><td class="row-actions" data-label="Actions"><a class="icon-btn" href="{{ route('visits.show',$visit) }}" title="View visit" aria-label="View visit"><i data-icon="eye"></i></a>@can('admin')<a class="icon-btn" href="{{ route('visits.edit',$visit) }}" title="Edit visit" aria-label="Edit visit"><i data-icon="edit"></i></a>@endcan @if(!$visit->check_out_at)<form method="POST" action="{{ route('visits.checkout',$visit) }}">@csrf @method('PATCH')<button class="icon-btn" title="Check out visitor" aria-label="Check out visitor"><i data-icon="logout"></i></button></form>@endif @can('admin')<form method="POST" action="{{ route('visits.destroy',$visit) }}" data-confirm="Permanently delete this visit record?">@csrf @method('DELETE')<button class="icon-btn danger" title="Delete visit" aria-label="Delete visit"><i data-icon="trash"></i></button></form>@endcan</td></tr>@empty<tr><td colspan="5" class="empty"><div class="empty-symbol"><i data-icon="visits"></i></div><h3>No visits to show</h3><p>Try another search or welcome your next visitor.</p><a class="btn" href="{{ route('visits.create') }}">Create a check-in</a></td></tr>@endforelse
</tbody></table></div><div class="register-footer"><span>{{ $visits->total() ? 'Showing '.$visits->firstItem().' - '.$visits->lastItem().' of '.$visits->total().' visits' : 'No matching records' }}</span><div class="pagination">{{ $visits->links() }}</div></div></div>
@endsection
