@extends('layouts.app')
@section('title','Visit Details')
@section('subtitle','A complete view of this visit.')
@section('content')
<a class="back-link" href="{{ route('visits.index') }}">&larr; Back to visitor log</a>
<div class="visit-overview"><div class="visit-identity">@if($visit->photo_path)<a class="photo-link" href="{{ route('visits.photo',$visit) }}" data-view-photo aria-label="Open visitor photo"><img class="visit-photo" src="{{ route('visits.photo',$visit) }}" alt="{{ $visit->visitor_name }}"></a>@else<div class="visit-photo initial">{{ strtoupper(substr($visit->visitor_name,0,1)) }}</div>@endif<div><span class="eyebrow">VISITOR PASS #{{ str_pad($visit->id,5,'0',STR_PAD_LEFT) }}</span><h2>{{ $visit->visitor_name }}</h2><span class="badge {{ $visit->check_out_at?'gray':'green' }}">{{ $visit->check_out_at?'Checked out':'Currently inside' }}</span></div></div><div class="visit-primary-actions">@can('admin')<a class="btn" href="{{ route('visits.edit',$visit) }}"><i data-icon="edit"></i> Edit visit</a>@endcan @if(!$visit->check_out_at)<form method="POST" action="{{ route('visits.checkout',$visit) }}">@csrf @method('PATCH')<button class="btn primary"><i data-icon="logout"></i> Check out visitor</button></form>@endif</div></div>
<div class="visit-detail-layout"><div class="visit-main"><section class="panel visit-section"><div class="section-title"><span class="section-icon"><i data-icon="users"></i></span><div><h2>Meeting details</h2><p>The person and purpose behind this visit.</p></div></div><div class="host-block"><span class="avatar">{{ strtoupper(substr($visit->employee->name,0,1)) }}</span><div><small>MEETING WITH</small><h3>{{ $visit->employee->name }}</h3><p>{{ $visit->employee->designation ? $visit->employee->designation.' · ' : '' }}{{ $visit->employee->company->name }}</p></div></div><div class="visit-purpose"><span class="eyebrow">PURPOSE OF VISIT</span><p>{{ $visit->purpose }}</p></div>@if($visit->notes)<div class="visit-notes"><span class="eyebrow">INTERNAL NOTES</span><p>{{ $visit->notes }}</p></div>@endif</section><section class="panel visit-section"><div class="section-title"><span class="section-icon"><i data-icon="visits"></i></span><div><h2>Visitor information</h2><p>Identity and contact details.</p></div></div><dl class="contact-grid"><div><dt>ID / CNIC / Passport</dt><dd>{{ $visit->id_card_number }}</dd></div><div><dt>Phone number</dt><dd>{{ $visit->visitor_phone ?: 'Not provided' }}</dd></div><div><dt>Email address</dt><dd>{{ $visit->visitor_email ?: 'Not provided' }}</dd></div></dl></section></div>
<aside class="visit-side"><section class="panel visit-section"><div class="section-title"><h2>Visit timeline</h2><i data-icon="visits"></i></div><ol class="visit-timeline"><li class="complete"><span class="timeline-label">Checked in</span><strong>{{ $visit->check_in_at->format('h:i A') }}</strong><small>{{ $visit->check_in_at->format('l, d M Y') }}</small></li><li class="{{ $visit->check_out_at?'complete':'pending' }}"><span class="timeline-label">{{ $visit->check_out_at?'Checked out':'Awaiting departure' }}</span>@if($visit->check_out_at)<strong>{{ $visit->check_out_at->format('h:i A') }}</strong><small>{{ $visit->check_out_at->format('l, d M Y') }}</small>@else<p>The visitor is still in the office.</p>@endif</li></ol><div class="visit-duration"><span class="eyebrow">TIME IN OFFICE</span><strong>{{ $visit->durationLabel() }}</strong><small>{{ $visit->check_out_at ? 'Total visit duration' : 'Elapsed so far - visitor still inside' }}</small></div><div class="recorded-by"><span class="eyebrow">CHECKED IN BY</span><p>{{ $visit->receptionist->name }}</p></div></section>@can('admin')<div class="record-options"><span>Record management</span><form method="POST" action="{{ route('visits.destroy',$visit) }}" data-confirm="Permanently delete this visit record?">@csrf @method('DELETE')<button class="icon-btn danger" title="Delete visit record" aria-label="Delete visit record"><i data-icon="trash"></i></button></form></div>@endcan</aside></div>
@endsection
