<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','Dashboard') &middot; Visitor Desk</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"><link rel="stylesheet" href="{{ asset('css/identity.css') }}"><script src="{{ asset('js/app.js') }}" defer></script><script src="{{ asset('js/camera.js') }}" defer></script></head>
<body><a class="skip-link" href="#page-content">Skip to content</a><button class="nav-overlay" aria-label="Close navigation" data-close-nav></button><aside class="sidebar" id="navigation"><a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark"><i data-icon="visits"></i></span><span>visitor<span class="brand-light">desk</span><small>ARRIVALS & CONNECTIONS</small></span></a><div class="eyebrow nav-label">WORKSPACE</div><nav aria-label="Main navigation">
@foreach(['dashboard'=>['dashboard','Overview','grid'],'visits'=>['visits.index','Visitor log','visits'],'employees'=>['employees.index','Employees','users']] as $section=>$item)
<a class="{{ request()->routeIs($section === 'dashboard' ? 'dashboard' : $section.'.*') ? 'active' : '' }}" @if(request()->routeIs($section === 'dashboard' ? 'dashboard' : $section.'.*')) aria-current="page" @endif href="{{ route($item[0]) }}"><i data-icon="{{ $item[2] }}" aria-hidden="true"></i><span>{{ $item[1] }}</span></a>
@endforeach
@can('admin')
@foreach(['reports'=>['reports.index','Reports','visits'],'users'=>['users.index','Users & roles','users']] as $section=>$item)<a class="{{ request()->routeIs($section.'.*')?'active':'' }}" href="{{ route($item[0]) }}"><i data-icon="{{ $item[2] }}"></i><span>{{ $item[1] }}</span></a>@endforeach
@endcan
</nav><div class="sidebar-note"><span class="live-dot"></span><b>Ready for arrivals</b><p>A thoughtful welcome.<br>A well-organized workplace.</p></div><div class="sidebar-user"><div class="avatar">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</div><div><b>{{ auth()->user()->name }}</b><small>{{ auth()->user()->isAdmin() ? 'Administrator' : 'Desk staff' }}</small></div><form method="POST" action="{{ route('logout') }}">@csrf<button title="Log out" aria-label="Log out"><i data-icon="logout"></i></button></form></div></aside>
<main><header class="topbar"><button class="menu" data-toggle-nav aria-label="Open navigation" aria-controls="navigation" aria-expanded="false"><i data-icon="menu"></i></button><div class="breadcrumb">Workspace <span>/</span> <b>@yield('title','Dashboard')</b></div><div class="topbar-status"><span class="live-dot"></span> Reception open <span class="topbar-date">{{ now()->format('D, d M Y') }}</span></div></header><section class="content" id="page-content" tabindex="-1"><div class="page-heading"><div><span class="eyebrow">VISITOR MANAGEMENT</span><h1>@yield('title','Dashboard')</h1><p>@yield('subtitle','Manage office visitors and meetings')</p></div>@if(request()->routeIs('dashboard','visits.index','visits.show'))<a class="btn primary" href="{{ route('visits.create') }}"><i data-icon="plus"></i> New check-in</a>@elseif(request()->routeIs('employees.index'))<a class="btn primary" href="{{ route('employees.create') }}"><i data-icon="plus"></i> Add employee</a>@elseif(request()->routeIs('users.index'))<a class="btn primary" href="{{ route('users.create') }}"><i data-icon="plus"></i> Add user</a>@elseif(request()->routeIs('companies.index'))<a class="btn primary" href="{{ route('companies.create') }}"><i data-icon="plus"></i> Add company</a>@endif</div>@if(session('success'))<div class="alert success" role="status">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert error" role="alert">{{ session('error') }}</div>@endif @if($errors->any())<div class="alert error" role="alert"><b>Please correct the following:</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')<footer class="page-footer"><span>Visitor Desk</span><span>A better welcome, every day.</span></footer></section></main><dialog id="delete-dialog" class="delete-dialog" aria-labelledby="delete-title" aria-describedby="delete-description delete-note"><div class="delete-dialog-top"><span class="delete-symbol"><i data-icon="trash"></i></span><button type="button" class="icon-btn" data-delete-cancel aria-label="Close delete confirmation">&times;</button></div><h2 id="delete-title">Delete this record?</h2><p id="delete-description"></p><p id="delete-note">This action cannot be undone.</p><div class="delete-dialog-actions"><button type="button" class="btn" data-delete-cancel autofocus>Cancel</button><button type="button" class="btn delete-confirm" data-delete-accept><i data-icon="trash"></i> Delete record</button></div></dialog><dialog id="photo-viewer" aria-label="Visitor photo"><div class="photo-toolbar"><strong>Visitor photo</strong><form method="dialog"><button class="icon-btn" aria-label="Close photo viewer">&times;</button></form></div><img alt="Visitor photo" data-full-photo><a class="btn" data-photo-original target="_blank" rel="noopener">Open original image</a></dialog>@stack('scripts')</body></html>
